export const ART_DATA = [
  {
    name: "father of jack",
    info: "some random text about this art",
    filename: "fatherofjack.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965236/jack-the-space-cat/fatherofjack_xyeioo.jpg",
    publicId: "jack-the-space-cat/fatherofjack_xyeioo.jpg"
  },
  {
    name: "Jack 1",
    info: "some random text about this art",
    filename: "jack1.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965236/jack-the-space-cat/jack1_yc35br.jpg",
    publicId: "jack-the-space-cat/jack1_yc35br.jpg",
  },
  {
    name: "son of jack",
    info: "some random text about this art",
    filename: "sonofjack.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965224/jack-the-space-cat/sonofjack_eobxxu.jpg",
    publicId: "jack-the-space-cat/sonofjack_eobxxu.jpg",
  },
  {
    name: "shut up wesley",
    info: "some random text about this art",
    filename: "shutupwesley.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965226/jack-the-space-cat/shutupwesley_b9dmja.jpg",
    publicId: "jack-the-space-cat/shutupwesley_b9dmja.jpg",
  },
  {
    name: "jack vs rick",
    info: "some random text about this art",
    filename: "jackvrick.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965227/jack-the-space-cat/jackvrick_l2zsq5.jpg",
    publicId: "jack-the-space-cat/jackvrick_l2zsq5.jpg",
  },
  {
    name: "jackraiser",
    info: "some random text about this art",
    filename: "jackraiser.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965227/jack-the-space-cat/jackraiser_bsd0ff.jpg",
    publicId: "jack-the-space-cat/jackraiser_bsd0ff.jpg",
  },
  {
    name: "Jack or Groucho Marx?",
    info: "some random text about this art",
    filename: "jackoumarx.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965226/jack-the-space-cat/jackoumarx_bub2rd.jpg",
    publicId: "jack-the-space-cat/jackoumarx_bub2rd.jpg",
  },
  {
    name: "jack on hoth",
    info: "some random text about this art",
    filename: "jackonhoth.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965225/jack-the-space-cat/jackonhoth_qmswg8.jpg",
    publicId: "jack-the-space-cat/jackonhoth_qmswg8.jpg",
  },
  {
    name: "jack on a date",
    info: "some random text about this art",
    filename: "jackonadate.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965229/jack-the-space-cat/jackonadate_sodpi8.jpg",
    publicId: "jack-the-space-cat/jackonadate_sodpi8.jpg",
  },
  {
    name: "jack on the couch",
    info: "some random text about this art",
    filename: "jackcouch.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965231/jack-the-space-cat/jackcouch_jxfv6i.jpg",
    publicId: "jack-the-space-cat/jackcouch_jxfv6i.jpg",
  },
  {
    name: "jackball",
    info: "some random text about this art",
    filename: "jackball.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965231/jack-the-space-cat/jackball_prwewz.jpg",
    publicId: "jack-the-space-cat/jackball_prwewz.jpg",
  },
  {
    name: "jack and the gang 2",
    info: "some random text about this art",
    filename: "jackandthegang2.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965234/jack-the-space-cat/jackandthegang2_f625kq.jpg",
    publicId: "jack-the-space-cat/jackandthegang2_f625kq.jpg",
  },
  {
    name: "jack and the gang",
    info: "some random text about this art",
    filename: "jackandthegang.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965234/jack-the-space-cat/jackandthegang_dazqfz.jpg",
    publicId: "jack-the-space-cat/jackandthegang_dazqfz.jpg",
  },
  {
    name: "jack and morty",
    info: "some random text about this art",
    filename: "jackandmorty.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965234/jack-the-space-cat/jackandmorty_miflm2.jpg",
    publicId: "jack-the-space-cat/jackandmorty_miflm2.jpg",
  },
  {
    name: "jack and bear",
    info: "some random text about this art",
    filename: "jackandbear.jpg",
    medium: "digital", 
    url: "https://res.cloudinary.com/dhvaidpl9/image/upload/v1616965235/jack-the-space-cat/jackandbear_pqvv2g.jpg",
    publicId: "jack-the-space-cat/jackandbear_pqvv2g.jpg",
  }
]